CREATE TABLE RFQs (
  id INT IDENTITY(1,1) PRIMARY KEY,
  project NVARCHAR(255) NOT NULL,
  supplier NVARCHAR(255) NOT NULL,
  dueDate DATE NOT NULL,
  createdAt DATETIME DEFAULT GETDATE()
);

CREATE TABLE RFQLines (
  id INT IDENTITY(1,1) PRIMARY KEY,
  rfqId INT NOT NULL REFERENCES RFQs(id) ON DELETE CASCADE,
  description NVARCHAR(255) NOT NULL,
  quantity INT NOT NULL
);

CREATE TABLE SupplierResponses (
  id INT IDENTITY(1,1) PRIMARY KEY,
  rfqId INT NOT NULL REFERENCES RFQs(id) ON DELETE CASCADE,
  data NVARCHAR(MAX) NOT NULL,
  createdAt DATETIME DEFAULT GETDATE()
);
